version: "3"

services:
  pgsql1:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "pgsql1"
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data:
